[versions]
metrics = "3.1.0"

junit-jupiter-engine = "5.12.1"

[libraries]
metrics = { module = "org.bstats:bstats-bukkit", version.ref = "metrics" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }

paper = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.18" }
paper-run = { id = "xyz.jpenilla.run-paper", version = "2.3.1" }

yml = { id = "de.eldoria.plugin-yml.bukkit", version = "0.8.0" }

shadow = { id = "com.gradleup.shadow", version = "9.1.0" }
